### ISSUE TITLE
Returning a Hashie::Mash response isn't useful

### ISSUE THREAD

**Issue by eric-pigeon** [avadev/AvaTax-REST-V2-Ruby-SDK#8]
The default response is a Hashie::Mash of the body instead of returning the Faraday::Response.  Since the response is lost, you can't check the response code or successfulness of API calls.

for reference
```
    def request(method, path, options)
      response = connection.send(method) do |request|
        case method
        when :get, :delete
          request.url(URI.encode(path), options)
        when :post, :put
          request.path = URI.encode(path)
          request.headers['Content-Type'] = 'application/json'
          request.body = options.to_json unless options.empty?
        end
      end

      ::Hashie::Mash.new response.body
    end
```

**Comment by marcus** [comment]
The gem no longer returns a Hashie::Mash.

**Comment by BenAkroyd** [comment]
I believe @eric-pigeon  's underlying issue was the lack of headers, status code, etc. Changing the data type does not address this.

Faraday is a very common way to deal with http responses, and it seems reasonable to return the entire Faraday::Response.

Could there perhaps be  config setting to return the full faraday response object? 
```
if return_faraday_response
  response
else
  response.body
end
```

**Comment by marcus** [comment]
I'm open to that change. @BenAkroyd if you have a PR, we can look at it. Otherwise, @han8909227 would you be interested in making this change?

**Comment by han8909227** [comment]
@marcus Yeah, I can make this change sometime next week

**Comment by marcus** [comment]
This will be fixed in the next release, likely in ~1 week.
